/**
 * LIS Member Requests Data Loader
 *
 * Provides functions to load LIS-scraped member request data
 * for display in legislator cards.
 */

import type { LegislatorCardData } from './cardTypes';

// Import JSON data files
// Note: These will be generated by the scraper script
import lisMR2024Raw from 'src/data/lis_member_requests_2024.json';
import lisMR2025Raw from 'src/data/lis_member_requests_2025.json';

const lisMR2024 = lisMR2024Raw as Record<string, LegislatorCardData>;
const lisMR2025 = lisMR2025Raw as Record<string, LegislatorCardData>;

/**
 * Get LIS Member Request data for a specific legislator and year
 * 
 * @param lisId - LIS member code (e.g., "H336")
 * @param year - Session year (2024 or 2025)
 * @returns LegislatorCardData if found, null otherwise
 */
export function getLisMemberRequestsForYear(
  lisId: string,
  year: 2024 | 2025
): LegislatorCardData | null {
  const source = year === 2024 ? lisMR2024 : lisMR2025;
  const data = source[lisId];

  return data ?? null;
}

/**
 * Get all available LIS Member Request data for a year
 * 
 * @param year - Session year (2024 or 2025)
 * @returns Record of all legislator data keyed by LIS ID
 */
export function getAllLisMemberRequestsForYear(
  year: 2024 | 2025
): Record<string, LegislatorCardData> {
  return year === 2024 ? lisMR2024 : lisMR2025;
}

/**
 * Check if LIS data exists for a legislator and year
 * 
 * @param lisId - LIS member code
 * @param year - Session year
 * @returns true if data exists, false otherwise
 */
export function hasLisMemberRequestData(
  lisId: string,
  year: 2024 | 2025
): boolean {
  const source = year === 2024 ? lisMR2024 : lisMR2025;
  return lisId in source;
}

